<?php
/* @var Magestore\Multivendor\Block\Vendor $block */
?>
<?php
$collection = $block->getVendorCollection();
?>
<div class="vendor-list">

    <div class="vendor row">
            <?php
            foreach ($collection as $vendorModel) : ?>
                <div class="col-lg-4">
                    <a href="<?php echo $block->getStoreManager()->getStore()->getUrl('multivendor/vendor/view') . 'id/' . $vendorModel->getId(); ?>">
                     <div class="card" >
                        <?php
                        $img = $block->getMediaUrlImage($vendorModel->getLogo());
                        ?>
                        <img class="card-img-top" src="<?php echo $img; ?>" alt="<?php echo $vendorModel->getName();?>" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title"><?php echo $vendorModel->getName(); ?></h5>
                            <p class="card-text"><?php echo $vendorModel->getDescription(); ?></p>
                        </div>
                    </div>
                    </a>
                </div>

            <?php endforeach; ?>

<!--        --><?php
        $result = $collection->toArray();

        var_dump(json_encode($result));
//        ?>

    </div>



</div>